import type { Person, Relationship, TreeSummary } from './types'

export const initialTrees: TreeSummary[] = [
  {
    id: 'ladyzhenko-family',
    title: 'Род Ладыженко',
    surname: 'Ладыженко',
    members: 24,
    lastUpdated: 'сегодня',
    privacy: 'private',
  },
  {
    id: 'siberian-branch',
    title: 'Сибирская ветка',
    surname: 'Георгиевы',
    members: 13,
    lastUpdated: '2 дня назад',
    privacy: 'shared',
  },
  {
    id: 'public-archive',
    title: 'Публичный архив семьи',
    surname: 'Домбровские',
    members: 51,
    lastUpdated: 'на прошлой неделе',
    privacy: 'public',
  },
]

export const initialPersons: Person[] = [
  {
    id: 'pavel',
    firstName: 'Павел',
    lastName: 'Ладыженко',
    years: '1908-1981',
    place: 'Тобольск',
    note: 'Корневая персона ветки. В карточке храним короткую биографическую подсказку.',
    branch: 'Северная линия',
    generation: 0,
    x: 280,
    y: 80,
  },
  {
    id: 'anna',
    firstName: 'Анна',
    lastName: 'Ладыженко',
    years: '1912-1996',
    place: 'Тюмень',
    note: 'Супруга Павла. Мягкая карточка должна легко читаться даже при плотной схеме.',
    branch: 'Северная линия',
    generation: 0,
    x: 520,
    y: 80,
  },
  {
    id: 'nikolai',
    firstName: 'Николай',
    lastName: 'Ладыженко',
    years: '1934-2011',
    place: 'Омск',
    note: 'Сын Павла и Анны. Для MVP показываем только основное.',
    branch: 'Северная линия',
    generation: 1,
    x: 220,
    y: 270,
  },
  {
    id: 'maria',
    firstName: 'Мария',
    lastName: 'Ладыженко',
    years: '1939-2017',
    place: 'Омск',
    note: 'Дочь Павла и Анны.',
    branch: 'Северная линия',
    generation: 1,
    x: 480,
    y: 270,
  },
  {
    id: 'vera',
    firstName: 'Вера',
    lastName: 'Георгиева',
    years: '1940-2020',
    place: 'Новосибирск',
    note: 'Партнёр Николая. Важна лёгкость интерфейса, без ярких акцентов.',
    branch: 'Сибирская ветка',
    generation: 1,
    x: 740,
    y: 270,
  },
  {
    id: 'elena',
    firstName: 'Елена',
    lastName: 'Ладыженко',
    years: '1965-н.в.',
    place: 'Екатеринбург',
    note: 'Живая персона. В будущем тут будет приватность для публичного режима.',
    branch: 'Сибирская ветка',
    generation: 2,
    x: 600,
    y: 470,
  },
]

export const initialRelationships: Relationship[] = [
  { id: 'r1', source: 'pavel', target: 'anna', kind: 'partner' },
  { id: 'r2', source: 'pavel', target: 'nikolai', kind: 'parent-child' },
  { id: 'r3', source: 'anna', target: 'nikolai', kind: 'parent-child' },
  { id: 'r4', source: 'pavel', target: 'maria', kind: 'parent-child' },
  { id: 'r5', source: 'anna', target: 'maria', kind: 'parent-child' },
  { id: 'r6', source: 'nikolai', target: 'vera', kind: 'partner' },
  { id: 'r7', source: 'nikolai', target: 'elena', kind: 'parent-child' },
  { id: 'r8', source: 'vera', target: 'elena', kind: 'parent-child' },
]
